name: Build & Upload

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-15

    steps:
      - name : Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.38.6

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.2'

      - name: Install dependancies
        run: |
          flutter clean
          flutter pub get

      - name: Install iOS dependencies
        run: |
          cd iOS
          pod install --repo-update
          cd ..

      - uses: nickwph/apple-build-certificate-action@v1
        with:
          certificate-base64: ${{ secrets.APPLE_CERTIFICATE }}
          certificate-password: ${{ secrets.APPLE_CERT_PASSWORD }}

      - uses: nickwph/apple-provisioning-profile-action@v1
        with:
          profile-base64: ${{ secrets.APPLE_PROVISIONING_PROFILE }}

      - name: Build iOS Archive
        run: |
          xcodebuild archive \
          -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -archivePath build/ios/archive/Runner.xcarchive \
          -allowProvisioningUpdates \
          -destination 'generic/platform=iOS'

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist

      - name: Show built IPA files
        run: ls -l build/ios/ipa

      - name: Upload dSYM to Firebase Crashlytics
        run: |
          cd build/ios/archive/Runner.xcarchive/dSYMs
          zip -r ../../dsym.zip *.dSYM
          cd -
          ios/Pods/FirebaseCrashlytics/upload-symbols \
            -gsp ios/Runner/GoogleService-Info.plist \
            -p ios build/ios/archive/dsym.zip

      - name: Upload to App Store
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/ios/ipa/flutter_app.ipa
          issuer-id: ${{ secrets.APP_STORE_API_ISSUER_ID }}
          api-key-id: ${{ secrets.APP_STORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APP_STORE_API_KEY }}

  build_android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v4

       - name: Setup JDK
         uses: actions/setup-java@v4
         with:
           distribution: 'zulu'
           java-version: '17'

       - name: Decode Android Keystore
         run: echo "${{ secrets.keystoreBase64 }}" | base64 --decode > android/app/keystore.jks
  
       - name: Setup Flutter
         uses: subosito/flutter-action@v2
         with:
           channel: stable
           flutter-version: 3.38.6

       - name: Install dependancies
         run: flutter pub get

       - name: Set up env vars for keystore
         run: |
           echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTOREPASSWORD }}" >> $GITHUB_ENV
           echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
           echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

       - name: Build APK
         run: flutter build appbundle --release

       - name: Deploy to Google Play
         uses: r0adkll/upload-google-play@v1
         with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_CREDENTIALS }}
          packageName: *APP PACKAGE NAME HERE*
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: completed
